version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    ignore:
      # While OTel Android is experimental and has frequent breaking changes, don't upgrade it.
      - dependency-name: "io.opentelemetry*"
      # Our RN SDK doesn't work with the latest versions of the Kotlin compiler
      - dependency-name: "org.jetbrains.kotlin*"
